# Generated by Django 3.2 on 2021-06-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.CharField(default='Customer', max_length=150, verbose_name='group'),
        ),
    ]
